### ISSUE TITLE
Define functional specifications

### ISSUE THREAD

**Issue by RyanSchw** [PurdueElectricRacing/TestBench#1]
This question is primarily for: @josh05201997 @mflanag @bsmrdel (but @AdamBusch @jacklecroy could maybe provide insights on how to best use the `unittest` Python module?)

What's the overall goal of the main testbench? My initial thoughts are below, but let me know if this is different from what you're thinking:

- Export class to be used as wrapper for other STM based projects
- The whole project file can be loaded on to the RasPi (instead of just the python files)
  - In the future, we could potentially use the RasPi to flash code to the board, further automating this process?

For example, below would be the example file structure of a STM project
```
ExampleSTM
│   README.md
│   ExampleSTM.ioc 
│
└───Inc
│   │   main.h
|   │   (etc)
└───Src
|   │   main.c
|   │   (etc)
└───Test
    │   ExampleSTM_Dashboard_test.py
    |   (etc)
```

Then in `ExampleSTM_Dashboard_test.py`
```python
from TestBench import STM32F4 as board
import unittest

class TestCallResponse(unittest.TestCase):
  
  def test_start(self):
    board.sendCAN(0x123) # Start button pressed
    response = board.expectCAN(0x123)
    self.assertTrue(response) # The expected CAN should be received by the board

if __name__ == '__main__':
  unittest.main()
  board.reportResults()
```

What would be most useful for development?

**Comment by mflanag** [comment]
So i think that sounds good from an overall view of how we should test code. I like the concept of being able to actually flash code automatically and test it that would be pretty convenient. 

But i do think that we need to also come up with what are the main things that we need to test for the main module. It might be better to have a dedicated software meeting to determine how we want to make it portable across projects.

**Comment by RyanSchw** [comment]
Yeah, to break down the issue, here's what I think one option could look like for the workflow:

1. Load code onto RasPi and use UI to test against flashed STM board (initial creation of library, create the actual tester functions)
2. Add ability to flash code to STM32 once loaded onto RasPi
3. Add wireless server host to RasPi so that you can just load files on to RasPi and wirelessly execute
4. Integrate with CI 

Would be cool if a few years down the road we could do virtual testing and hard-code testing based on a pull request.
See [#3 on this blog](https://blog.jumper.io/manual-to-automated-testing-in-embedded-software/) for the types of test cases we could do. I've reached out to Jumper.io in the past, so they may be able to help guide us for the hardware testing.

**Comment by RyanSchw** [comment]
Another example of what the goal could be: https://blog.jumper.io/stm32-continuous-integration/

**Comment by AdamBusch** [comment]
Would it be helpful to open separate issues for each of the list items above? I think that could lead to more containerized code if each issue is developed separate from the other. 
I think we should be trying to implement this more across the board.

**Comment by RyanSchw** [comment]
Definitely. Let's meet on Saturday to find a resolution about the end goal and the minimum viable product. From there, I'll break down the separate issues, create some examples of the results we'd want (and what we're testing for in the first place), etc.

**Comment by RyanSchw** [comment]
So functions that will be available are as follows (for the candapter unit test module):

* `sendSerial`
* `receiveSerial`
* `sendCAN`
* `receiveCAN`
* `setGPIO(pin, value)`
* `receiveGPIO(pin, value)`

In addition, the following constants will be set for clarity:
This will require an additional import statement `from TestBench import gpio` or as part of `import TestBench`

* `gpio.HIGH`
* `gpio.LOW`


In addition, future commands can be added like:

* `setAnalog(pin, value)`

**Comment by RyanSchw** [comment]
Updated example script:
```python
from TestBench import STM32F4
import unittest

board = STM32F4()

class TestCallResponse(unittest.TestCase):
  def test_start(self):
    board.sendCAN(0x123) # Start button pressed
    response = board.expectCAN(0x123)
    self.assertTrue(response) # The expected CAN should be received by the board

if __name__ == '__main__':
  unittest.main()
  board.reportResults()
```

**Comment by RyanSchw** [comment]
```python
from TestBench import STM32F4
import unittest

class TestCallResponse(unittest.TestCase):
  def test_start(self):
    board = STM32F4()
    board.sendCAN(0x123)
    self.assertEqual(0x123, board.receiveCAN())

if __name__ == '__main__':
  unittest.main()
```

I think we want a new `STM32F4()` every time, so that all tests are considered completely independent of each other.

Note: `expectCAN()` and similar were changed to `receiveCAN()` so that it would be clear that was not the assertion statement.

**Comment by RyanSchw** [comment]
Did GPIO using: https://opensourceforu.com/2017/07/introduction-raspberry-pi-gpio-programming-using-python/
